### ISSUE TITLE
Issue with debug information

### ISSUE THREAD

**Issue by Integralist** [gruntjs/grunt-contrib-sass#47]
Hi,

I'm using `grunt-contrib-sass ~0.3.0` and the following is my Gruntfile Sass task...

``` js
sass: {
    dist: {
        options: {
            style: 'compressed',
            require: ['./app/styles/sass/helpers/url64.rb']
        },
        expand: true,
        cwd: './app/styles/sass/',
        src: ['*.scss'],
        dest: './app/styles/',
        ext: '.css'
    },
    dev: {
        options: {
            style: 'expanded',
            debugInfo: true,
            lineNumbers: true,
            require: ['./app/styles/sass/helpers/url64.rb']
        },
        expand: true,
        cwd: './app/styles/sass/',
        src: ['*.scss'],
        dest: './app/styles/',
        ext: '.css'
    }
},
```

...the compiled `sass:dev` CSS doesn't look to be displaying the debugging information correctly.

Here is my Sass content...

``` sass
body {
    border: 10px solid blue;
    p {
        border: 10px solid green;
    }
}
```

...and here is the output...

``` css
@media -sass-debug-info{filename{}line{font-family:\000031}}
body {
  border: 10px solid blue;
}
@media -sass-debug-info{filename{}line{font-family:\000033}}
body p {
  border: 10px solid green;
}
```

...that looks broken to me.

The numbers after the first `3` are the actual line number for that particular rule but things like the filename aren't displayed?

Is this just a bug that needs to be fixed (not sure if this is a Sass bug or a Grunt-Sass plugin bug) or have I missed something my side?

Thanks.

M.
